<?php


namespace api\modules\admin\services;


use api\modules\admin\forms\AdminRoleForm;
use api\modules\admin\models\AdminRole;

class AdminRoleService extends Service
{
    /**
     * @var string
     */
    public $formClass = AdminRoleForm::class;

    /**
     * @param array $data
     * @return AdminRoleForm
     * @throws \yii\base\UserException
     */
    public function store($data = [])
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }

    /**
     * 获取管理员角色ID集合
     * @param $adminId
     * @return array
     */
    public function getAdminRoleId($adminId)
    {
        return AdminRole::find()->select(['role_id'])
            ->notDelete()
            ->andWhere(['admin_id' => $adminId])
            ->column()?:[];
    }

    /**
     * 根据条件删除
     * @param $where
     */
    public function delByWhere($where)
    {
        AdminRole::updateAll(['is_del'=>AdminRole::IS_DEL_YES, 'updated_at' => time()], $where);
    }
}