<?php


namespace api\modules\admin\services;


use api\modules\admin\forms\RoleForm;
use api\modules\admin\models\Role;
use api\modules\admin\resources\RoleResource;
use api\modules\admin\search\RoleSearch;
use yii\base\UserException;
use yii\data\ActiveDataProvider;

class RoleService extends Service
{
    /**
     * @var string
     */
    public $formClass = RoleForm::class;

    /**
     * @var string
     */
    public $resourceClass = RoleResource::class;

    /**
     * @var string
     */
    public $searchClass = RoleSearch::class;

    /**
     * 管理员列表
     * @param array $params
     * @return array|ActiveDataProvider
     * @throws UserException
     */
    public function index($params = [])
    {
        return parent::index($params); // TODO: Change the autogenerated stub
    }

    /**
     * 添加管理角色
     * @param array $data
     * @return RoleForm
     * @throws UserException
     */
    public function store($data = [])
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }

    /**
     * 更新管理角色
     * @param array $data
     * @return RoleForm
     * @throws UserException
     */
    public function update($data = [])
    {
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    /**
     * 删除管理角色
     * @param array $data
     * @return RoleForm
     * @throws UserException
     */
    public function destroy($data = [])
    {
        return parent::destroy($data); // TODO: Change the autogenerated stub
    }
}