<?php


namespace api\modules\admin\services;


use api\modules\admin\models\Admin;
use api\services\ServiceAbstract;

class Service extends ServiceAbstract
{
    /**
     * @return \yii\web\IdentityInterface|null|Admin
     */
    protected function user()
    {
        return \Yii::$app->user->identity;
    }

    /**
     * @return array
     */
    protected function baseParams()
    {
        return array_merge(parent::baseParams(), [
            'shop_id' => $this->user()->shop_id ?? 0,
        ]); // TODO: Change the autogenerated stub
    }
}