<?php


namespace api\modules\admin\forms;


use api\modules\admin\models\AdminRole;

class AdminRoleForm extends AdminRole
{
    /**
     * @return array|array[]
     */
    public function rules()
    {
        return [
            [['role_id', 'admin_id'], 'required'],
        ];
    }

    /**
     * @return array|array[]
     */
    public function scenarios()
    {
        return array_merge(parent::scenarios(), [
            self::SCENARIO_STORE => ['role_id', 'admin_id']
        ]); // TODO: Change the autogenerated stub
    }
}