<?php


namespace api\modules\admin\forms;


use api\modules\admin\models\Menu;

class MenuForm extends Menu
{
    public function rules()
    {
        return [
            [['id', 'title', 'path'], 'required'],
            [['icon'], 'string'],
            [['sort', 'pid'], 'integer'],
        ];
    }

    public function scenarios()
    {
        return array_merge(parent::scenarios(), [
            self::SCENARIO_STORE => ['title', 'icon', 'sort', 'pid', 'path'],
            self::SCENARIO_UPDATE => ['id', 'title', 'icon', 'sort', 'pid', 'path'],
        ]); // TODO: Change the autogenerated stub
    }
}