<?php


namespace api\modules\admin\forms;


use api\modules\admin\models\Role;

class RoleForm extends Role
{
    /**
     * @return array|array[]
     */
    public function rules()
    {
        return [
            [['id', 'title', 'tag'], 'required'],
            [['status'], 'in', 'range' => [self::STATUS_OK, self::STATUS_FREEZE]]
        ];
    }

    /**
     * @return array|array[]
     */
    public function scenarios()
    {
        return array_merge(parent::scenarios(), [
            self::SCENARIO_STORE => ['title', 'tag'],
            self::SCENARIO_UPDATE => ['id', 'title', 'status', 'tag'],
            self::SCENARIO_DESTROY => ['id'],
        ]); // TODO: Change the autogenerated stub
    }
}