<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/6/19
 * Time: 10:51
 */
namespace common\traits;

use common\helpers\BaseHelper;


/**
 * Trait ModelFieldTypeTrait
 * @package common\traits
 *
 * @property int $is_del
 */
trait ModelFieldTypeTrait
{
    public static $fieldType;

    /**
     * 设置字段类型
     * @param $type
     * @return $this
     */
    public function setFieldType( $type )
    {
        static::$fieldType = $type;

        return $this;
    }

    /**
     * 通用的fields方法
     * @return array|false|mixed
     */
    public function fields()
    {
        $method = 'field' . BaseHelper::convertUnderline(static::$fieldType, true);
        if ( method_exists($this, $method) ) {
            return call_user_func([$this, $method]);
        }
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function destroy()
    {
        if (is_array($this->id)) {
            return self::updateAll(['is_del' => self::IS_DEL_YES, 'updated_at' => time()], ['id' => $this->id]);
        }
        $this->is_del = self::IS_DEL_YES;
        return $this->save();
    }
}