<?php


namespace api\modules\shop\services;


use api\components\ActiveRecord;
use api\modules\shop\forms\CustomerAddressForm;
use api\modules\shop\models\CustomerAddress;
use api\modules\shop\resources\CustomerAddressResource;
use api\modules\shop\search\CustomerAddressSearch;
use yii\base\UserException;

class CustomerAddressService extends Service
{
    /**
     * @var string
     */
    public $searchClass = CustomerAddressSearch::class;

    /**
     * @var string
     */
    public $formClass = CustomerAddressForm::class;

    /**
     * @var string
     */
    public $resourceClass = CustomerAddressResource::class;

    /**
     * @param array $params
     * @return array|\yii\data\ActiveDataProvider
     * @throws UserException
     */
    public function index($params = [])
    {
        return parent::index($params); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $id
     * @return mixed
     * @throws UserException
     */
    public function show($id)
    {
        return parent::show($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return CustomerAddressForm
     * @throws UserException
     */
    public function store($data = [])
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return CustomerAddressForm
     * @throws UserException
     */
    public function update($data = [])
    {
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return CustomerAddressForm
     * @throws UserException
     */
    public function destroy($data = [])
    {
        return parent::destroy($data); // TODO: Change the autogenerated stub
    }

    /**
     * 删除所有的客户地址
     * @param $customerIds
     * @return int
     */
    public function delAllCustomerAddress($customerIds)
    {
        return CustomerAddress::updateAll([
            'is_del' => ActiveRecord::IS_DEL_YES,
            'updated_at' => time(),
            'updated_by' => \Yii::$app->user->id
        ], [
            'customer_id' => $customerIds
        ]);
    }
}