<?php


namespace api\modules\shop\services;


use api\components\ActiveRecord;
use api\modules\shop\forms\CustomerForm;
use api\modules\shop\models\CustomerAddress;
use api\modules\shop\resources\CustomerResource;
use api\modules\shop\search\CustomerSearch;
use yii\base\UserException;
use yii\data\ActiveDataProvider;

class CustomerService extends Service
{
    /**
     * @var string
     */
    public $formClass = CustomerForm::class;

    /**
     * @var string
     */
    public $resourceClass = CustomerResource::class;

    /**
     * @var string
     */
    public $searchClass = CustomerSearch::class;

    /**
     * 客户列表
     * @param array $params
     * @return array|ActiveDataProvider
     * @throws UserException
     */
    public function index($params = [])
    {
        return parent::index($params); // TODO: Change the autogenerated stub
    }

    /**
     * 客户详情
     * @param int $id
     * @return CustomerResource
     * @throws UserException
     */
    public function show($id)
    {
        return parent::show($id); // TODO: Change the autogenerated stub
    }

    /**
     * 添加客户
     * @param array $data
     * @return CustomerForm
     * @throws UserException
     */
    public function store($data = [])
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }

    /**
     * 更新客户
     * @param array $data
     * @return CustomerForm
     * @throws UserException
     */
    public function update($data = [])
    {
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    /**
     * 删除客户
     * @param array $data
     * @return CustomerForm
     * @throws UserException
     */
    public function destroy($data = [])
    {
        $form = parent::destroy($data); // TODO: Change the autogenerated stub
        if (!$form->hasErrors()) {
            CustomerAddress::updateAll([
                'is_del' => ActiveRecord::IS_DEL_YES,
                'updated_at' => time(),
                'updated_by' => \Yii::$app->user->id
            ], [
                'customer_id' => $data['id']
            ]);
        }
        return $form;
    }

}