<?php


namespace api\modules\shop\services;


use api\modules\shop\forms\GoodsUnitForm;
use api\modules\shop\resources\GoodsUnitResource;
use api\modules\shop\search\GoodsUnitSearch;
use yii\base\UserException;
use yii\data\ActiveDataProvider;

class GoodsUnitService extends Service
{
    /**
     * @var string
     */
    public $formClass = GoodsUnitForm::class;

    /**
     * @var string
     */
    public $resourceClass = GoodsUnitResource::class;

    /**
     * @var string
     */
    public $searchClass = GoodsUnitSearch::class;

    /**
     * 商品单位列表
     * @param array $params
     * @return array|ActiveDataProvider
     * @throws UserException
     */
    public function index($params = [])
    {
        return parent::index($params); // TODO: Change the autogenerated stub
    }

    /**
     * 商品单位详情
     * @param int $id
     * @return GoodsUnitResource
     * @throws UserException
     */
    public function show($id)
    {
        return parent::show($id); // TODO: Change the autogenerated stub
    }

    /**
     * 添加商品单位
     * @param array $data
     * @return GoodsUnitForm
     * @throws UserException
     */
    public function store($data = [])
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }

    /**
     * 更新商品单位
     * @param array $data
     * @return GoodsUnitForm
     * @throws UserException
     */
    public function update($data = [])
    {
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    /**
     * 删除商品单位
     * @param array $data
     * @return GoodsUnitForm
     * @throws UserException
     */
    public function destroy($data = [])
    {
        return parent::destroy($data); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function select()
    {
        return GoodsUnitResource::find()
            ->select('title')
            ->andWhere(['shop_id' => $this->user()->shop_id])
            ->notDelete()
            ->orderBy('id desc')
            ->all();
    }

}