<?php


namespace api\modules\shop\services;


use api\modules\shop\forms\OrderGoodsForm;
use api\modules\shop\resources\OrderGoodsResource;
use api\modules\shop\search\OrderGoodsSearch;

class OrderGoodsService extends Service
{
    /**
     * @var string
     */
    public $formClass = OrderGoodsForm::class;

    /**
     * @var string
     */
    public $resourceClass = OrderGoodsResource::class;

    /**
     * @var string
     */
    public $searchClass = OrderGoodsSearch::class;

    /**
     * @param array $params
     * @return array|\yii\data\ActiveDataProvider
     * @throws \yii\base\UserException
     */
    public function index($params = [])
    {
        return parent::index($params); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return OrderGoodsForm
     * @throws \yii\base\UserException
     */
    public function store($data = [])
    {
        /** @var OrderGoodsForm $form */
        $form = parent::store($data); // TODO: Change the autogenerated stub

        // 扣除库存
        $service = new GoodsService();
        $service->deductStock([
            'id' => $form->goods_id,
            'stock' => $form->book_num
        ]);

        return $form;
    }
}