<?php


namespace api\modules\shop\caches;


use api\caches\CacheAbstract;
use api\modules\shop\models\Goods;

class GoodsCache extends CacheAbstract
{
    /**
     * @var bool 不需要缓存标识
     */
    public $noGroup = true;

    /**
     * @return string
     */
    public static function tableName(): string
    {
        return Goods::tableName();// TODO: Implement tableName() method.
    }

    /**
     * @return array|string[]
     */
    protected function likeFields()
    {
        return array_merge(parent::likeFields(), [
            'created_start',
            'created_end'
        ]); // TODO: Change the autogenerated stub
    }
}