<?php


namespace api\modules\shop\caches;


use api\caches\CacheAbstract;
use api\modules\shop\models\Order;

class OrderCache extends CacheAbstract
{
    /**
     * @var bool 不需要缓存标识
     */
    public $noGroup = true;

    /**
     * @return string
     */
    public static function tableName(): string
    {
        return Order::tableName();// TODO: Implement tableName() method.
    }

    /**
     * @return array|string[]
     */
    protected function likeFields()
    {
        return parent::likeFields(); // TODO: Change the autogenerated stub
    }
}