<?php


namespace api\modules\shop\forms;


use api\modules\shop\models\CustomerAddress;

class CustomerAddressForm extends CustomerAddress
{
    /**
     * @return array|array[]
     */
    public function rules()
    {
        return [
            [['id', 'customer_id', 'consignee', 'contact_tel', 'address'], 'required']
        ];
    }

    /**
     * @return array|array[]
     */
    public function scenarios()
    {
        return array_merge(parent::scenarios(), [
            self::SCENARIO_STORE => ['customer_id', 'consignee', 'contact_tel', 'address'],
            self::SCENARIO_UPDATE => ['id', 'customer_id', 'consignee', 'contact_tel', 'address'],
            self::SCENARIO_DESTROY => ['id']
        ]); // TODO: Change the autogenerated stub
    }
}