<?php


namespace api\modules\shop\forms;


use api\modules\shop\models\Customer;
use common\traits\FormModelValidate;

class CustomerForm extends Customer
{
    use FormModelValidate;

    /**
     * @return array|array[]
     */
    public function rules()
    {
        return [
            [['id', 'name', 'shop_id'], 'required'],
            [['phone'], 'uniqNotDel'],
            [['phone'], 'checkPhone'],
            [['loc_number'], 'checkLocNumber'],
            [['wx'], 'checkWxId'],
            [['wx', 'loc_number', 'phone'], 'default', 'value' => '']
        ];
    }

    /**
     * @return array|array[]
     */
    public function scenarios()
    {
        return array_merge(parent::scenarios(), [
            self::SCENARIO_STORE => ['shop_id', 'name', 'phone', 'wx', 'loc_number'],
            self::SCENARIO_UPDATE => ['id', 'name', 'phone', 'wx', 'loc_number'],
            self::SCENARIO_DESTROY => ['id'],
        ]); // TODO: Change the autogenerated stub
    }
}